name: express-better-auth-poc
services:
  mysql:
    image: mysql:8.4
    container_name: express-better-auth-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: my_app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    platform: linux/amd64

  mailpit:
    image: axllent/mailpit:latest
    container_name: express-better-auth-mailpit
    restart: unless-stopped
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  mysql_data:
